### ISSUE TITLE
Review the testing suite for inconsistencies while testing

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-elasticsearch#101]
## Is your feature request related to a problem?
CI failed randomly due to a test that raced

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

## Priority
Nice to Have

## Additional context
[This is the error that happened twice](https://github.com/newrelic/nri-elasticsearch/files/7435215/1.log)

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
