### ISSUE TITLE
Metrics are all exposed as gauges so monitoring is extremely difficult, such as indices.indexingOperationsFailed

### ISSUE THREAD

**Issue by driskell** [newrelic/nri-elasticsearch#103]
## Description
Some metrics such as indices.indexingOperationsFailed are useful for monitoring but they are treated as a gauge and so it is a forever increasing value. For example after an incident it may stand at 12000 but stay at that value for a long time with everything working fine. However, because the value of 12000 is stored in New Relic One it's not something you can alert on. You cannot say, "Alert if the value increases again".

## Expected Behavior
Usually these metrics would be a delta so you can alert on a delta value and also graph the failures over time and see 0s where everything is working fine.

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
N/A

## Steps to Reproduce
Install and look at failed indexing operations graph. Trigger some manual indexing that fails and see that the graph begins to have a large value and flat lines on that large value and never returns to 0.

## Your Environment
Elasticsearch 7.x

## Additional context
N/A

**Comment by carlossscastro** [comment]
Hi @driskell 

Thanks for writing in!

We would suggest opening a ticket with our Technical Support team or post this question in our community.
We should have other ways to address your specific use case using NRQL functions.

Thanks!

**Comment by driskell** [comment]
Hi @carlossscastro 

I initially thought of it as a bug as this was outlier amongst the integrations which all seem to implement the RATE source type, whereas this one is completely different and not consistent with zero RATE metrics.

Although NRQL can solve this potentially (and yes I may need to go to the community likely to see how to do that with alerting) - I’ve never had to do this before.

It would be great if it could be fixed in the integration. Appreciate it would be a breaking change so perhaps behind a flag to enable “v2” metrics or something… (I personally wouldn’t be keen on duplicating metrics)

I would propose a PR but due to the above it would not be a clear cut change so I would only proceed if there was agreement on approach (and of course time allowing.)

Thanks for your time.

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.

We encourage community contributions and are happy to collaborate on design proposals and pull requests. See our PR guidelines in the README. If you have any further questions or comments about this, please let us know by replying to this issue.

**Comment by driskell** [comment]
Hi @davidgit

This issue renders usage of the plugin useless to us from a monitoring perspective. Was there anything I could clarify? As I am uncertain the usefulness of this in its current state. It seems a significant bug.
