### ISSUE TITLE
Elasticsearch DB infra metrics are not getting captured in kuberentes environment

### ISSUE THREAD

**Issue by Debanjan05** [newrelic/nri-elasticsearch#114]
Elasticsearch agent is not able to capture cluster and node level metrics in k8s env but in local system or docker env its able to capture all the metrics.

Env - Robin kubernetes environment.

APM Agent Language - nri-elasticsearch, nri-couchbase - Elasticsearch and Couchbase Infra Agent
APM Agent Version - v4.3.4
Operating System - kubernetes
Operating System Version
Frameworks your app is using - Collector is in Java and database storage is elasticsearch.

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
