### ISSUE TITLE
Binding hardcoded to localhost

### ISSUE THREAD

**Issue by tischler** [newrelic/nri-elasticsearch#23]
https://github.com/newrelic/nri-elasticsearch/blob/071cb7f7000893adc200b96849c81ae7c9360fa2/src/elasticsearch.go#L50

We have a situation where ES is not bound to localhost, but another host so I believe this should either accept the hostname attribute, or another attribute for what is considered "localhost".

**Comment by cpheps** [comment]
Closed by #24
