### ISSUE TITLE
Node Naming

### ISSUE THREAD

**Issue by cpheps** [newrelic/nri-elasticsearch#41]
##### Description of the problem

Investigate using the `name` field rather than the `hostname` field for naming nodes.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by edward-of-clt** [comment]
This appears to still be an issue. `node.hostname` returns the host IP address. 

The `elasticsearch.yml` configuration defines the hostname. The box also has the hostname configured.
