### ISSUE TITLE
used_disk_percent metric

### ISSUE THREAD

**Issue by msahota14** [newrelic/nri-elasticsearch#60]
##### Description of the problem
Missing `used_disk_percent` metric

The `used_disk_percent` metric is missing from nri-elasticsearch. This is found in the `fs` parameter, an example from nodeStatsMetricsResult.json:

     		"fs": {
				"timestamp": 1533662802396,
				"total": {
					"total_in_bytes": 164705353728,
					"free_in_bytes": 162707742720,
					"available_in_bytes": 162707742720,
					"operations": 10,
					"read_kilobytes": 39485,
					"read_operations": 39486,
					"write_kilobytes": 298341,
					"write_operations": 2384089
				},
				"least_usage_estimate": {
					"path": "/var/lib/elasticsearch/nodes/0",
					"total_in_bytes": 164705353728,
					"available_in_bytes": 162707742720,
					"used_disk_percent": 1.2128391474747815
				},
				"most_usage_estimate": {
					"path": "/var/lib/elasticsearch/nodes/0",
					"total_in_bytes": 164705353728,
					"available_in_bytes": 162707742720,
					"used_disk_percent": 1.2128391474747815

Is it possible this could be added?

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by camdencheek** [comment]
Fixed by #61
