### ISSUE TITLE
Crashes on "closed" indices

### ISSUE THREAD

**Issue by gannett-ggreer** [newrelic/nri-elasticsearch#68]
If a monitored Elastichsearch cluster has a "closed" index then the integration command fails.

## Description
```
$ /var/db/newrelic-infra/custom-integrations/bin/nri-elasticsearch [...]
[INFO] Collecting cluster metrics.
[INFO] Collecting node metrics
[INFO] Collecting common metrics.
[ERR] There was an error populating metrics for common metrics: status code 400 - received error of type 'index_closed_exception' from Elasticsearch: closed
[INFO] Collecting indices metrics
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6b9c4f]

goroutine 1 [running]:
main.setIndicesStatsMetricsResponse(0xc0001282c0, 0xc000534000, 0x31, 0x3f, 0x0, 0xc0003fb0c0, 0x18, 0x0)
	/go/src/github.com/newrelic/nri-elasticsearch/metrics.go:164 +0x18f
main.populateIndicesMetrics(0xc0001282c0, 0x7ad960, 0xc000116bc0, 0x0, 0xc0003fb0c0, 0x18, 0x1, 0x1)
	/go/src/github.com/newrelic/nri-elasticsearch/metrics.go:131 +0x192
main.populateMetrics(0xc0001282c0, 0x7ad960, 0xc000116bc0, 0x704909, 0x0)
	/go/src/github.com/newrelic/nri-elasticsearch/metrics.go:33 +0x311
main.main()
	/go/src/github.com/newrelic/nri-elasticsearch/elasticsearch.go:50 +0x14c
```

## Expected Behavior
Closed indices don't prevent metrics collection.

## Steps to Reproduce
Run `nri-elasticsearch` with an Elasticsearch cluster having a closed index.

## Your Environment
`nri-elasticsearch` v4.3.3 with Elasticsearch v7.9.0

**Comment by gsanchezgavier** [comment]
Hi @gannett-ggreer  thanks for reporting this bug. I submitted a PR to handle this nil pointer. 
From my research i found that the root cause could be related to[ this issue ](https://github.com/elastic/elasticsearch/issues/32238).
As a quick workaround you can set the `CollectIndices` to `false` in order to avoid the crash and keep sending Nodes and Cluster metrics
