### ISSUE TITLE
Skipping SSL validation is not as easy as it could be

### ISSUE THREAD

**Issue by arvdias** [newrelic/nri-elasticsearch#69]
## Is your feature request related to a problem? Please describe.

Currently in order to skip server certificate verification, we need to setup an ssl_alternative_hostname and a ca_bundle_dir (or file).  

## Feature Description

The ssl_alternative_hostname might not be working in all cases, so we should add a simple boolean flag (InsecureSkipVerify) to skip all server certificate validation (which is what most users want) like most other integrations have,

## Priority
[Really Want]

**Comment by alvarocabanas** [comment]
This PR in the infra-integrations-sdk, adds the possibilitiy to pass the flag, and once merged, it can be applied to this integration. https://github.com/newrelic/infra-integrations-sdk/pull/270/files
