### ISSUE TITLE
Unsupported data type '[]interface {}' for yaml key

### ISSUE THREAD

**Issue by AndreyZaslavskiyWMG** [newrelic/nri-elasticsearch#71]
While runnung nri-elasticsearch integration I'm getting this errors:
[DEBUG] Unsupported data type '[]interface {}' for yaml key discovery.seed_hosts
[DEBUG] Unsupported data type '[]interface {}' for yaml key cluster.initial_master_nodes

## Description
My config file for elasticsearch have these lines: 
---
discovery.seed_hosts:
  - ip-address1
  - ip-address2

cluster.initial_master_nodes:
  - node-name1
  - node-name2
---
## Your Environment
Simple 2-node cluster

I've checked elastic docs for typos, etc, but found that it's fine

**Comment by carlossscastro** [comment]
Hi @AndreyZaslavskiyWMG 

I'm going to move this to closed, since this seemed like a configuration issue and we haven't heard from you since.
If you still need help on this let us know.

Thanks!
